# Generated by Django 5.0.2 on 2025-02-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_call_app', '0002_tournament_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
